FROM node:16-alpine

USER node
RUN rm -rf '/usr/node/app/node_modules'

WORKDIR '/usr/node/app'


COPY --chown=node:node ./package.json .

RUN npm config set unsafe-perm true
RUN npm install



COPY --chown=node:node . .


RUN mkdir -p /usr/node/app/node_modules/.cache
RUN chmod 777 -R /usr/node/app/node_modules/.cache
RUN chown -R node:node /usr/node/app


USER node
CMD ["npm", "run", "start"]